# Generated by Django 6.0.6 on 2026-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('contact_form', 'Contact form'), ('newsletter', 'Newsletter signup'), ('resource_download', 'Resource download'), ('other', 'Other')], default='contact_form', max_length=30)),
                ('is_handled', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
