# Generated by Django 6.0.6 on 2026-06-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=32)),
                ('score', models.PositiveSmallIntegerField()),
                ('level', models.CharField(max_length=12)),
                ('category_scores', models.JSONField(default=dict)),
                ('key_counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'data risk snapshot',
                'ordering': ['-created_at'],
            },
        ),
    ]
