# Generated by Django 6.0.6 on 2026-06-15 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(db_index=True, help_text='Machine code for the kind of job, e.g. "contact_email".', max_length=50)),
                ('title', models.CharField(help_text='Short human title shown to the user, already translated.', max_length=150)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Processing'), ('success', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('result_url', models.CharField(blank=True, max_length=300)),
                ('error_message', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'background task',
                'verbose_name_plural': 'background tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
