# Generated by Django 6.0.6 on 2026-06-15 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='When on, outgoing mail uses the SMTP details below instead of the environment defaults.')),
                ('smtp_host', models.CharField(blank=True, help_text='SMTP server host.', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(blank=True, help_text='SMTP port, e.g. 465 (SSL) or 587 (TLS).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('use_ssl', models.BooleanField(default=True, help_text='Use implicit SSL (port 465).')),
                ('use_tls', models.BooleanField(default=False, help_text='Use STARTTLS (port 587). Not with SSL.')),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('default_from_email', models.CharField(blank=True, help_text='"From" header. Blank uses DEFAULT_FROM_EMAIL.', max_length=200)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Optional Reply-To address.', max_length=254)),
                ('test_recipient', models.EmailField(blank=True, help_text='Address used by the "Send test email" admin action.', max_length=254)),
                ('last_test_status', models.CharField(blank=True, max_length=10)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'email settings',
                'verbose_name_plural': 'email settings',
            },
        ),
        migrations.CreateModel(
            name='OperationalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookings_enabled', models.BooleanField(default=True, help_text='Allow visitors to submit booking requests.')),
                ('tools_enabled', models.BooleanField(default=True, help_text='Allow the free diagnostic tools to run.')),
                ('task_poll_interval_ms', models.PositiveIntegerField(default=1500, help_text='How often the status component polls, in milliseconds.', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(15000)])),
                ('long_task_timeout_s', models.PositiveIntegerField(default=420, help_text='Reference timeout for long background jobs, in seconds.', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3600)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'operational settings',
                'verbose_name_plural': 'operational settings',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, help_text='Public brand name. Blank uses the SITE_NAME setting.', max_length=120)),
                ('canonical_base_url', models.URLField(blank=True, help_text='Absolute base URL, e.g. https://bidatia.xyz. Blank uses SITE_BASE_URL.')),
                ('public_contact_email', models.EmailField(blank=True, help_text='Address shown to visitors. Blank uses CONTACT_EMAIL.', max_length=254)),
                ('admin_recipient_email', models.EmailField(blank=True, help_text='Where contact/booking notifications are sent. Blank uses CONTACT_NOTIFICATION_EMAIL.', max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Public WhatsApp/phone number. Blank uses CONTACT_WHATSAPP.', max_length=40)),
                ('business_address', models.CharField(blank=True, help_text='City / address line shown publicly.', max_length=200)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Reserved flag for a future maintenance banner/page. Does not take pages offline on its own.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Master switch for the AI interpretation layer on tool reports. When on, AI still runs only if a model is configured here or via the TOOLS_AI_MODEL environment value; turn off to force it off.')),
                ('provider', models.CharField(blank=True, default='ollama', help_text='AI provider key, e.g. "ollama".', max_length=40)),
                ('model_name', models.CharField(blank=True, help_text='Model id, e.g. "qwen3.5:9b". Blank uses TOOLS_AI_MODEL.', max_length=80)),
                ('request_timeout', models.PositiveIntegerField(blank=True, help_text='Overall generation deadline in seconds. Blank uses TOOLS_AI_TIMEOUT.', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(900)])),
                ('thinking_budget', models.PositiveIntegerField(blank=True, help_text='Seconds of free-form reasoning before the strict-JSON pass. 0 disables thinking. Blank uses TOOLS_AI_THINKING_BUDGET.', null=True, validators=[django.core.validators.MaxValueValidator(600)])),
                ('max_output_tokens', models.PositiveIntegerField(blank=True, help_text='Optional cap on generated tokens.', null=True, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(32000)])),
                ('temperature', models.FloatField(blank=True, help_text='Creativity 0–2. Lower is more deterministic.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('system_instructions', models.TextField(blank=True, help_text='Skills / system instructions prepended to the model prompt. Internal — never shown to visitors.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
