# Generated by Django 6.0.6 on 2026-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalconfiguration',
            name='show_tool_diagnostics',
            field=models.BooleanField(default=False, help_text='Show technical error details on the free-tool progress pages when a scan fails (for debugging). Staff always see them; turn this on to show them to all visitors too, then turn it off again once the issue is solved.'),
        ),
    ]
