# Generated by Django 6.0.6 on 2026-06-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_operationalconfiguration_show_tool_diagnostics'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='last_ai_test_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='last_ai_test_message',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='last_ai_test_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
