# Generated by Django 6.0.6 on 2026-06-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('text_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('related_type', models.CharField(blank=True, max_length=60)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'email log',
                'ordering': ['-created_at'],
            },
        ),
    ]
