"""
Django settings for bidatia project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in the environment for any non-local deployment.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-j(=%j_8z9-g!1(ll$v19q69kqqanc#)7i#ay=0tu0)%9eh$zvk',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local development; set DJANGO_DEBUG=False in production.
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')

# Required by Django for HTTPS POSTs (admin, forms) behind a domain. Example:
# DJANGO_CSRF_TRUSTED_ORIGINS=https://bidatia.xyz,https://www.bidatia.xyz
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    # django-unfold: modern admin theme. Must be listed BEFORE
    # 'django.contrib.admin' so its templates/static override the defaults.
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',

    # 'modeltranslation' must come BEFORE 'django.contrib.admin' so the admin
    # picks up the translation-aware ModelAdmin classes.
    'modeltranslation',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    'core',
    'services',
    'booking',
    'leads',
    'blog',
    'pages',
    'tools_core',
    'tool_studio_xray',
    'tool_erp_rescue',
    'tool_odoo_detector',
    'tool_chaos_calc',
    'tool_data_risk',
    'glossary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files straight from Gunicorn in
    # production (no separate web server needed). Must come right after
    # SecurityMiddleware and before everything else.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # LocaleMiddleware must come after SessionMiddleware and before CommonMiddleware.
    # It activates the language from the URL prefix / session / Accept-Language header.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Keep authenticated responses (which may include the staff toolbar) out of
    # any shared/edge cache. Must run after AuthenticationMiddleware.
    'core.middleware.PrivateAuthenticatedCacheMiddleware',
]

ROOT_URLCONF = 'bidatia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings',
                'core.context_processors.seo',
                'core.context_processors.admin_toolbar',
            ],
        },
    },
]

WSGI_APPLICATION = 'bidatia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Spanish is the default/main language (Bidatia's primary audience).
# English and Arabic are also offered. Visiting "/" redirects to the visitor's
# browser language, falling back to Spanish.
LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
    ('ar', _('Arabic')),
]

# Where Django looks for the project's translation catalogues (.po/.mo files).
LOCALE_PATHS = [BASE_DIR / 'locale']

# django-modeltranslation: translate database content (Service, BlogPost, …).
# English is the source language; missing es/ar values fall back to English.
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_LANGUAGES = ('en', 'es', 'ar')
MODELTRANSLATION_FALLBACK_LANGUAGES = ('en',)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Leading slash is required so {% static %} URLs resolve correctly under the
# language-prefixed URLs (/en/, /es/, /ar/) produced by i18n_patterns.

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: compress collected static files (keeps original filenames, so
# hard-coded paths like those in site.webmanifest keep working).
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Business contact info (used across templates via core.context_processors)
SITE_NAME = 'Bidatia Business Systems'
# Short brand + division used for the logo lockup in the navbar/footer.
SITE_BRAND = 'Bidatia'
SITE_DIVISION = 'Business Systems'
SITE_TAGLINE = 'ERP, Odoo y datos gobernados con IA'
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', 'info@bidatia.xyz')
CONTACT_WHATSAPP = os.environ.get('CONTACT_WHATSAPP', '+34 911 23 45 67')
SITE_CITY = 'Madrid, España'

# Email (SMTP, environment-driven)
# Defaults to the console backend in development so no credentials are needed
# locally; in production it uses SMTP. Override DJANGO_EMAIL_BACKEND to force one.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'bidatia.xyz')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', True)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)  # SSL and TLS are mutually exclusive
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'info@bidatia.xyz')
# Never hardcode the password — set EMAIL_HOST_PASSWORD in the environment only.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Bidatia Business Systems <info@bidatia.xyz>')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', 'info@bidatia.xyz')

# Where contact/booking notifications are sent (To) and copied (Cc).
CONTACT_NOTIFICATION_EMAIL = os.environ.get('CONTACT_NOTIFICATION_EMAIL', 'info@bidatia.xyz')
CONTACT_NOTIFICATION_CC = env_list('CONTACT_NOTIFICATION_CC', '')

# Absolute base URL used to build admin links inside notification emails and as
# the canonical origin for SEO (canonical/hreflang/Open-Graph URLs in production).
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'https://bidatia.xyz')

# Optional absolute URL to a default social-share image (1200×630 recommended).
# Empty by default so no broken og:image/twitter:image is emitted until a real
# asset exists, e.g. OG_DEFAULT_IMAGE=https://bidatia.xyz/static/img/og.png
OG_DEFAULT_IMAGE = os.environ.get('OG_DEFAULT_IMAGE', '')


# ── Celery (background tasks for the free tools) ─────────────────────────────
# Broker is Redis, configured via REDIS_URL. Tool-run tasks receive Odoo
# credentials as ARGUMENTS, so two safety rules apply project-wide:
#   1. No result backend (task_ignore_result=True): nothing about a task —
#      args, kwargs, return values — is ever written to Redis.
#   2. Workers run at INFO log level; DEBUG-level celery logging can print
#      task arguments.
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
# Local development without Redis/worker: set CELERY_TASK_ALWAYS_EAGER=True to
# run tasks synchronously in the request process. Never enable in production.
CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', False)
CELERY_TASK_IGNORE_RESULT = True
CELERY_RESULT_EXTENDED = False  # never store args/kwargs metadata anywhere
CELERY_TASK_TIME_LIMIT = 420        # hard kill after 7 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 360   # leaves room for scan (~60s) + AI budget (180s)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = 'UTC'

# Daily cleanup: wipe result_json payloads of expired ToolRuns (rows are kept
# for analytics; only the report payload is removed). 03:30 UTC, low-traffic.
CELERY_BEAT_SCHEDULE = {
    'wipe-expired-tool-results': {
        'task': 'tools_core.tasks.wipe_expired_tool_results',
        'schedule': crontab(hour=3, minute=30),
    },
    # One gentle reminder before a report is wiped (never repeats per run).
    'send-report-expiry-reminders': {
        'task': 'tools_core.tasks.send_expiry_reminders',
        'schedule': crontab(minute=15),
    },
    # Monday-morning funnel digest for the founder.
    'send-founder-weekly-summary': {
        'task': 'tools_core.tasks.send_founder_weekly_summary',
        'schedule': crontab(hour=6, minute=0, day_of_week=1),
    },
    # Daily action report: the last 24 hours, every morning.
    'send-founder-daily-report': {
        'task': 'tools_core.tasks.send_founder_daily_report',
        'schedule': crontab(hour=6, minute=30),
    },
    # Monthly growth report: the previous calendar month, on the 1st.
    'send-founder-monthly-report': {
        'task': 'tools_core.tasks.send_founder_monthly_report',
        'schedule': crontab(hour=7, minute=0, day_of_month=1),
    },
}

# Optional external booking link (e.g. Calendly) for the tool-report CTA.
# Empty -> reports link to the internal booking flow instead.
TOOLS_BOOKING_URL = os.environ.get('TOOLS_BOOKING_URL', '')

# ── Local AI insights (Ollama) ────────────────────────────────────────────────
# A LOCAL model adds an interpretation layer to tool reports. It never decides
# scores/findings (those stay deterministic) and never receives credentials.
# Empty TOOLS_AI_MODEL disables the feature entirely (safe default for dev/CI).
# Production: TOOLS_AI_MODEL=qwen3.5:9b
OLLAMA_URL = os.environ.get('OLLAMA_URL', 'http://127.0.0.1:11434')
TOOLS_AI_MODEL = os.environ.get('TOOLS_AI_MODEL', '')
# Overall generation deadline. qwen3.x are THINKING models: cold load +
# reasoning can take a couple of minutes on first use.
TOOLS_AI_TIMEOUT = int(os.environ.get('TOOLS_AI_TIMEOUT', '180'))
# Seconds of free-form "live thinking" allowed before cutting to the fast
# strict-JSON answer. 0 = skip the thinking attempt entirely (fastest scans,
# progress page falls back to canned phrases).
TOOLS_AI_THINKING_BUDGET = int(os.environ.get('TOOLS_AI_THINKING_BUDGET', '60'))

# Cache aliases: 'default' stays in-process (fast, no infra needed);
# 'tools' is Redis-backed and SHARED between gunicorn and the Celery worker —
# used to stream the AI "thinking" note from the task to the progress page.
# Every consumer of 'tools' degrades gracefully when Redis is unavailable.
CACHES = {
    'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'},
    'tools': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://localhost:6379/0'),
    },
}


# Logging — surface email/notification failures to stderr without exposing them
# to visitors. Hosting platforms capture stderr; adjust handlers in production.
# Production 500s are emailed to ADMINS (AdminEmailHandler is a no-op when
# DEBUG is on, and a failed alert email never breaks the request itself).
ADMINS = [('Bidatia Business Systems', addr) for addr in
          env_list('DJANGO_ADMINS', CONTACT_NOTIFICATION_EMAIL)]

# Hot-lead alerts (instant internal emails when a tool surfaces a strong
# prospect). Falls back to ADMINS, then the contact notification address.
HOT_LEAD_RECIPIENTS = (env_list('HOT_LEAD_RECIPIENTS', '')
                       or [addr for _, addr in ADMINS]
                       or [CONTACT_NOTIFICATION_EMAIL])

# Founder daily/monthly reports. Defaults to the same inbox the weekly
# summary already uses; override with a comma-separated list when needed.
FOUNDER_REPORT_RECIPIENTS = (env_list('FOUNDER_REPORT_RECIPIENTS', '')
                             or [CONTACT_NOTIFICATION_EMAIL])

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'},
    },
    'formatters': {
        'simple': {'format': '[{asctime}] {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
        'mail_admins': {
            'class': 'django.utils.log.AdminEmailHandler',
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'include_html': False,
        },
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'bidatia': {'handlers': ['console', 'mail_admins'], 'level': 'INFO',
                   'propagate': False},
        'django.request': {'handlers': ['console', 'mail_admins'],
                           'level': 'ERROR', 'propagate': False},
    },
}

# Analytics loads in production only — local development and test runs must
# never pollute launch numbers. Override with ENABLE_ANALYTICS=0/1. The GA
# measurement id and Search Console verification token are env-driven so no
# third-party tracking id is ever committed to the repository.
GA_MEASUREMENT_ID = os.environ.get('GA_MEASUREMENT_ID', '')
GOOGLE_SITE_VERIFICATION = os.environ.get('GOOGLE_SITE_VERIFICATION', '')
ENABLE_ANALYTICS = (
    (not DEBUG)
    and os.environ.get('ENABLE_ANALYTICS', '1') != '0'
    and bool(GA_MEASUREMENT_ID)
)


# Production security hardening
# These only apply when DEBUG is off, so local development is unaffected.
# Assumes the app runs behind an HTTPS reverse proxy (Nginx / Cloudflare).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'


# ── Django Unfold admin theme ─────────────────────────────────────────────────
# Branding, brand-blue accent palette, a lightweight business dashboard and a
# workflow-oriented sidebar. No CDN: Unfold ships its own static assets.
UNFOLD = {
    'SITE_TITLE': 'Bidatia Business Systems',
    'SITE_HEADER': 'Bidatia',
    'SITE_SUBHEADER': _('Business Systems · ERP, Data & AI'),
    'SITE_URL': '/',
    'SITE_SYMBOL': 'database',  # Material Symbol used as the logo mark
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'SHOW_BACK_BUTTON': True,
    'DASHBOARD_CALLBACK': 'core.admin.dashboard_callback',
    'STYLES': [
        lambda request: static('admin_custom/admin.css'),
    ],
    # Bidatia anchor-blue accent (same palette as the public site), as
    # "R G B" channels. Tailwind blue scale, anchored on #2563eb (blue-600).
    'COLORS': {
        'primary': {
            '50': '239 246 255',
            '100': '219 234 254',
            '200': '191 219 254',
            '300': '147 197 253',
            '400': '96 165 250',
            '500': '59 130 246',
            '600': '37 99 235',
            '700': '29 78 216',
            '800': '30 64 175',
            '900': '30 58 138',
            '950': '23 37 84',
        },
    },
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
        'navigation': [
            {
                'title': _('Dashboard'),
                'items': [
                    {'title': _('Overview'), 'icon': 'dashboard', 'link': reverse_lazy('admin:index')},
                ],
            },
            {
                'title': _('Bookings'),
                'items': [
                    {'title': _('Consultation requests'), 'icon': 'event_available',
                     'link': reverse_lazy('admin:booking_consultationrequest_changelist')},
                    {'title': _('Availability slots'), 'icon': 'schedule',
                     'link': reverse_lazy('admin:booking_availabilityslot_changelist')},
                ],
            },
            {
                'title': _('Leads'),
                'items': [
                    {'title': _('Contact messages'), 'icon': 'mail',
                     'link': reverse_lazy('admin:leads_lead_changelist')},
                ],
            },
            {
                'title': _('Content'),
                'items': [
                    {'title': _('Services'), 'icon': 'design_services',
                     'link': reverse_lazy('admin:services_service_changelist')},
                    {'title': _('Insights'), 'icon': 'article',
                     'link': reverse_lazy('admin:blog_blogpost_changelist')},
                    {'title': _('Case studies'), 'icon': 'workspace_premium',
                     'link': reverse_lazy('admin:blog_casestudy_changelist')},
                ],
            },
            {
                'title': _('Administration'),
                'items': [
                    {'title': _('Users'), 'icon': 'person',
                     'link': reverse_lazy('admin:auth_user_changelist')},
                    {'title': _('Groups'), 'icon': 'group',
                     'link': reverse_lazy('admin:auth_group_changelist')},
                ],
            },
        ],
    },
}
