# Generated by Django 6.0.6 on 2026-06-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(help_text='Shown on cards and listing pages.', max_length=240)),
                ('description', models.TextField(help_text='Full description for the service detail page. One paragraph per line.')),
                ('outcome', models.CharField(blank=True, help_text='One-line outcome the client gets, e.g. "A clear, prioritized fix list within 5 days".', max_length=240)),
                ('icon', models.CharField(blank=True, help_text='Icon keyword used by the template, e.g. "audit", "module", "integration", "support".', max_length=50)),
                ('price_label', models.CharField(help_text='e.g. "From €350" or "€49 per session"', max_length=80)),
                ('delivery_time', models.CharField(blank=True, help_text='e.g. "3-5 business days" or "Scope-based"', max_length=120)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured services are highlighted on the homepage.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
