# Generated by Django 6.0.6 on 2026-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivery_time_ar',
            field=models.CharField(blank=True, help_text='e.g. "3-5 business days" or "Scope-based"', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_time_en',
            field=models.CharField(blank=True, help_text='e.g. "3-5 business days" or "Scope-based"', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_time_es',
            field=models.CharField(blank=True, help_text='e.g. "3-5 business days" or "Scope-based"', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(help_text='Full description for the service detail page. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(help_text='Full description for the service detail page. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(help_text='Full description for the service detail page. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='outcome_ar',
            field=models.CharField(blank=True, help_text='One-line outcome the client gets, e.g. "A clear, prioritized fix list within 5 days".', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='outcome_en',
            field=models.CharField(blank=True, help_text='One-line outcome the client gets, e.g. "A clear, prioritized fix list within 5 days".', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='outcome_es',
            field=models.CharField(blank=True, help_text='One-line outcome the client gets, e.g. "A clear, prioritized fix list within 5 days".', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_label_ar',
            field=models.CharField(help_text='e.g. "From €350" or "€49 per session"', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_label_en',
            field=models.CharField(help_text='e.g. "From €350" or "€49 per session"', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_label_es',
            field=models.CharField(help_text='e.g. "From €350" or "€49 per session"', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ar',
            field=models.CharField(help_text='Shown on cards and listing pages.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(help_text='Shown on cards and listing pages.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_es',
            field=models.CharField(help_text='Shown on cards and listing pages.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ar',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_es',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicefaq',
            name='answer_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicefaq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicefaq',
            name='answer_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicefaq',
            name='question_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicefaq',
            name='question_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicefaq',
            name='question_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='text_ar',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='text_en',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='text_es',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
