# Generated by Django 6.0.6 on 2026-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40, verbose_name='Phone / WhatsApp')),
                ('country', models.CharField(max_length=80)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ar', 'Arabic')], default='en', max_length=5)),
                ('consultation_type', models.CharField(choices=[('paid_consultation', 'Paid Odoo Consultation'), ('health_check', 'Odoo Health Check'), ('studio_cleanup', 'Odoo Studio Cleanup'), ('migration_assessment', 'Odoo Migration Assessment'), ('custom_module', 'Custom Odoo Module Development'), ('integration', 'Django ↔ Odoo Integration'), ('monthly_support', 'Monthly Odoo Support'), ('other', 'Other / Not sure yet')], max_length=30)),
                ('odoo_version', models.CharField(blank=True, max_length=40, verbose_name='Odoo version')),
                ('problem_summary', models.TextField(verbose_name='Problem summary')),
                ('preferred_datetime', models.CharField(help_text='Free text, e.g. "Weekday afternoons (Madrid time)"', max_length=120, verbose_name='Preferred date / time')),
                ('consent', models.BooleanField(default=False, verbose_name='I agree to be contacted about this request')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation request',
                'ordering': ['-created_at'],
            },
        ),
    ]
