# Generated by Django 6.0.6 on 2026-06-07 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='consultation_type',
            field=models.CharField(choices=[('intro_call', 'Free 20-minute Intro Call'), ('paid_consultation', 'Paid Odoo Consultation'), ('health_check', 'Odoo Health Check'), ('monthly_support', 'Monthly Odoo Support'), ('studio_cleanup', 'Odoo Studio Cleanup'), ('migration_assessment', 'Odoo Migration Assessment'), ('custom_module', 'Custom Odoo Module Development'), ('integration', 'Django ↔ Odoo Integration'), ('other', 'Other / Not sure yet')], max_length=30),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='preferred_datetime',
            field=models.CharField(blank=True, help_text='Free text, e.g. "Weekday afternoons (Madrid time)". Optional when a slot is selected.', max_length=120, verbose_name='Preferred date / time'),
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('intro_call', 'Free 20-minute Intro Call'), ('paid_consultation', 'Paid Odoo Consultation'), ('health_check', 'Odoo Health Check'), ('monthly_support', 'Monthly Odoo Support'), ('studio_cleanup', 'Odoo Studio Cleanup'), ('migration_assessment', 'Odoo Migration Assessment'), ('custom_module', 'Custom Odoo Module Development'), ('integration', 'Django ↔ Odoo Integration'), ('other', 'Other / Not sure yet')], max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='Europe/Madrid', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Availability slot',
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('consultation_type', 'date', 'start_time'), name='unique_slot_per_type_date_start')],
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='The availability slot the customer reserved, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='booking.availabilityslot'),
        ),
    ]
