# Generated by Django 6.0.6 on 2026-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_ar',
            field=models.TextField(help_text='Main article body. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(help_text='Main article body. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_es',
            field=models.TextField(help_text='Main article body. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ar',
            field=models.CharField(help_text='Short summary shown on the blog list page.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.CharField(help_text='Short summary shown on the blog list page.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_es',
            field=models.CharField(help_text='Short summary shown on the blog list page.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='approach_ar',
            field=models.TextField(help_text='What was done. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='approach_en',
            field=models.TextField(help_text='What was done. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='approach_es',
            field=models.TextField(help_text='What was done. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenge_ar',
            field=models.TextField(help_text='What problem the client had. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenge_en',
            field=models.TextField(help_text='What problem the client had. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenge_es',
            field=models.TextField(help_text='What problem the client had. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_summary_ar',
            field=models.CharField(help_text='e.g. "Mid-size distribution company, Spain" — keep it anonymous if needed.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_summary_en',
            field=models.CharField(help_text='e.g. "Mid-size distribution company, Spain" — keep it anonymous if needed.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_summary_es',
            field=models.CharField(help_text='e.g. "Mid-size distribution company, Spain" — keep it anonymous if needed.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='results_ar',
            field=models.TextField(help_text='Outcome / measurable results. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='results_en',
            field=models.TextField(help_text='Outcome / measurable results. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='results_es',
            field=models.TextField(help_text='Outcome / measurable results. One paragraph per line.', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
