# Generated by Django 6.0.6 on 2026-06-11 21:53

import django.db.models.deletion
import tools_core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('odoo_version_detected', models.CharField(blank=True, max_length=20)),
                ('odoo_edition_detected', models.CharField(blank=True, max_length=20)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('source_tool', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tool lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_slug', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connecting', 'Connecting'), ('collecting', 'Collecting'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('odoo_url', models.URLField()),
                ('odoo_db', models.CharField(max_length=120)),
                ('odoo_version', models.CharField(blank=True, max_length=20)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=tools_core.models.default_expires_at)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tools_core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
