# Generated by Django 6.0.6 on 2026-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connecting', 'Connecting'), ('collecting', 'Collecting'), ('analyzing', 'Analyzing'), ('ai_insights', 'AI insights'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
