# Generated by Django 6.0.6 on 2026-06-12 11:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_core', '0002_alter_toolrun_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answering', 'Answering'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tools_core.toolrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
