# Generated by Django 6.0.6 on 2026-06-12 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_core', '0003_reportquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(db_index=True, max_length=40)),
                ('event', models.CharField(db_index=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('visitor_key', models.CharField(blank=True, db_index=True, max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tools_core.toolrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
