# Generated by Django 6.0.6 on 2026-06-12 22:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_core', '0004_toolevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_slug', models.CharField(max_length=60)),
                ('level_code', models.CharField(choices=[('stable', 'Stable result (ERP Rescue Check)'), ('low_complexity', 'Low-risk result (Studio X-Ray)')], max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='tools_core.toolrun')),
            ],
            options={
                'verbose_name': 'health badge',
                'ordering': ['-created_at'],
            },
        ),
    ]
