# Generated by Django 6.0.6 on 2026-06-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_core', '0005_healthbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthbadge',
            name='level_code',
            field=models.CharField(choices=[('stable', 'Stable result (ERP Rescue Check)'), ('low_complexity', 'Low-risk result (Studio X-Ray)'), ('low_data_risk', 'Low data migration risk (Data Risk Profiler)')], max_length=30),
        ),
    ]
