# Generated by Django 6.0.6 on 2026-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_core', '0006_alter_healthbadge_level_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrun',
            name='diagnostic',
            field=models.TextField(blank=True),
        ),
    ]
